# Generated by Django 4.2.1 on 2023-05-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_test_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_teXt',
            new_name='question_text',
        ),
    ]
